### PR TITLE
updated URL,

### PR DESCRIPTION
**Pull request by LoveMyData**
refactor code to support multiple pages,
update README,
fixed issue #1

### CODE REVIEW

**Comment by LoveMyData** [comment]
https://morph.io/LoveMyData/Brimbank_City_Council

**Comment by JasonThomasData** [comment]
Nice, you've fixed it. Good work.

**Review by henare — APPROVED** [review]
Hey @LoveMyData you rewrote a Ruby scraper and made it simpler and better :gem: So you're a Ruby developer now :smile:

**Comment by henare** [comment]
@LoveMyData I just noticed that the associated issue #1 didn't automatically close when we merged this. If you include a line that says "Fixes #1" in the body of the pull request it will automatically close the issue. You can also include this in the commit message and it will work too.

**Pull request merged**
